create table article_entity (title varchar(255) not null, author varchar(255), content varchar(255), last_edited_on date, published_on date, primary key (title))
create table comment_entity (id  bigserial not null, body varchar(255), created timestamp, name varchar(255), article varchar(255), primary key (id))
alter table if exists comment_entity add constraint FKe9pj52iqvd78m67kkjruj6a3 foreign key (article) references article_entity
create table article_entity (title varchar(255) not null, author varchar(255), content varchar(255), last_edited_on date, published_on date, primary key (title))
create table comment_entity (id  bigserial not null, body varchar(255), created timestamp, name varchar(255), article varchar(255), primary key (id))
alter table if exists comment_entity add constraint FKe9pj52iqvd78m67kkjruj6a3 foreign key (article) references article_entity
create table article_entity (title varchar(255) not null, author varchar(255), content varchar(255), published_on timestamp, primary key (title))
create table comment_entity (id bigint generated by default as identity, author varchar(255), content varchar(255), created timestamp, article varchar(255), primary key (id))
alter table comment_entity add constraint FKe9pj52iqvd78m67kkjruj6a3 foreign key (article) references article_entity
create table article_entity (title varchar(255) not null, author varchar(255), content varchar(255), published_on timestamp, primary key (title))
create table comment_entity (id bigint generated by default as identity, author varchar(255), content varchar(255), created timestamp, article varchar(255), primary key (id))
alter table comment_entity add constraint FKe9pj52iqvd78m67kkjruj6a3 foreign key (article) references article_entity
create table article_entity (title varchar(255) not null, author varchar(255), content varchar(255), published_on timestamp, primary key (title))
create table comment_entity (id bigint generated by default as identity, author varchar(255), content varchar(255), created timestamp, article varchar(255), primary key (id))
alter table comment_entity add constraint FKe9pj52iqvd78m67kkjruj6a3 foreign key (article) references article_entity
create table article_entity (title varchar(255) not null, author varchar(255), content varchar(255), published_on timestamp, primary key (title))
create table comment_entity (id bigint generated by default as identity, author varchar(255), content varchar(255), created timestamp, article varchar(255), primary key (id))
alter table comment_entity add constraint FKe9pj52iqvd78m67kkjruj6a3 foreign key (article) references article_entity
create table article_entity (title varchar(255) not null, author varchar(255), content varchar(255), published_on timestamp, primary key (title))
create table comment_entity (id  bigserial not null, author varchar(255), content varchar(255), created timestamp, article varchar(255), primary key (id))
alter table if exists comment_entity add constraint FKe9pj52iqvd78m67kkjruj6a3 foreign key (article) references article_entity
create table article_entity (title varchar(255) not null, author varchar(255), content varchar(255), published_on timestamp, primary key (title))
create table comment_entity (id  bigserial not null, author varchar(255), content varchar(255), created timestamp, article varchar(255), primary key (id))
alter table if exists comment_entity add constraint FKe9pj52iqvd78m67kkjruj6a3 foreign key (article) references article_entity
create table article_entity (title varchar(255) not null, author varchar(255), content varchar(255), published_on timestamp, primary key (title))
create table comment_entity (id  bigserial not null, author varchar(255), content varchar(255), created timestamp, article varchar(255), primary key (id))
alter table if exists comment_entity add constraint FKe9pj52iqvd78m67kkjruj6a3 foreign key (article) references article_entity
create table article_entity (title varchar(255) not null, author varchar(255), content varchar(255), published_on timestamp, primary key (title))
create table comment_entity (id  bigserial not null, author varchar(255), content varchar(255), created timestamp, article varchar(255), primary key (id))
alter table if exists comment_entity add constraint FKe9pj52iqvd78m67kkjruj6a3 foreign key (article) references article_entity
create table article_entity (title varchar(255) not null, author varchar(255), content varchar(255), published_on timestamp, primary key (title))
create table comment_entity (id bigint generated by default as identity, author varchar(255), content varchar(255), created timestamp, article varchar(255), primary key (id))
alter table comment_entity add constraint FKe9pj52iqvd78m67kkjruj6a3 foreign key (article) references article_entity
create table article_entity (title varchar(255) not null, author varchar(255), content varchar(255), published_on timestamp, primary key (title))
create table comment_entity (id  bigserial not null, author varchar(255), content varchar(255), created timestamp, article varchar(255), primary key (id))
alter table if exists comment_entity add constraint FKe9pj52iqvd78m67kkjruj6a3 foreign key (article) references article_entity
create table article_entity (title varchar(255) not null, author varchar(255), content varchar(255), published_on timestamp, primary key (title))
create table comment_entity (id bigint generated by default as identity, author varchar(255), content varchar(255), created timestamp, article varchar(255), primary key (id))
alter table comment_entity add constraint FKe9pj52iqvd78m67kkjruj6a3 foreign key (article) references article_entity
create table article_entity (title varchar(255) not null, author varchar(255), content varchar(255), published_on timestamp, primary key (title))
create table comment_entity (id bigint generated by default as identity, author varchar(255), content varchar(255), created timestamp, article varchar(255), primary key (id))
alter table comment_entity add constraint FKe9pj52iqvd78m67kkjruj6a3 foreign key (article) references article_entity
create table article_entity (title varchar(255) not null, author varchar(255), content varchar(255), published_on timestamp, primary key (title))
create table comment_entity (id bigint generated by default as identity, author varchar(255), content varchar(255), created timestamp, article varchar(255), primary key (id))
alter table comment_entity add constraint FKe9pj52iqvd78m67kkjruj6a3 foreign key (article) references article_entity
create table article_entity (title varchar(255) not null, author varchar(255), content varchar(255), published_on timestamp, primary key (title))
create table comment_entity (id bigint generated by default as identity, author varchar(255), content varchar(255), created timestamp, article varchar(255), primary key (id))
alter table comment_entity add constraint FKe9pj52iqvd78m67kkjruj6a3 foreign key (article) references article_entity
create table article_entity (title varchar(255) not null, author varchar(255), content varchar(255), published_on timestamp, primary key (title))
create table comment_entity (id bigint generated by default as identity, author varchar(255), content varchar(255), created timestamp, article varchar(255), primary key (id))
alter table comment_entity add constraint FKe9pj52iqvd78m67kkjruj6a3 foreign key (article) references article_entity
create table article_entity (title varchar(255) not null, author varchar(255), content varchar(255), published_on timestamp, primary key (title))
create table comment_entity (id bigint generated by default as identity, author varchar(255), content varchar(255), created timestamp, article varchar(255), primary key (id))
alter table comment_entity add constraint FKe9pj52iqvd78m67kkjruj6a3 foreign key (article) references article_entity
create table article_entity (title varchar(255) not null, author varchar(255), content varchar(255), published_on timestamp, primary key (title))
create table comment_entity (id bigint generated by default as identity, author varchar(255), content varchar(255), created timestamp, article varchar(255), primary key (id))
alter table comment_entity add constraint FKe9pj52iqvd78m67kkjruj6a3 foreign key (article) references article_entity
create table article_entity (title varchar(255) not null, author varchar(255), content varchar(255), published_on timestamp, primary key (title))
create table comment_entity (id bigint generated by default as identity, author varchar(255), content varchar(255), created timestamp, article varchar(255), primary key (id))
alter table comment_entity add constraint FKe9pj52iqvd78m67kkjruj6a3 foreign key (article) references article_entity
create table article_entity (title varchar(255) not null, author varchar(255), content varchar(255), published_on timestamp, primary key (title))
create table comment_entity (id bigint generated by default as identity, author varchar(255), content varchar(255), created timestamp, article varchar(255), primary key (id))
alter table comment_entity add constraint FKe9pj52iqvd78m67kkjruj6a3 foreign key (article) references article_entity
